### ISSUE TITLE
"Microsoft" string replacement creates prominent "Contoso, Ltd. Defender for Cloud" feature in Azure portal

### ISSUE THREAD

**Issue by WilliamDAssafMSFT** [jonburchel/ScreenshotScrubber#8]
![image](https://user-images.githubusercontent.com/74387232/141208890-66c7e00e-4948-4838-bd64-f20db719481f.png)

Need a more sophisticated replacement to allow for "Microsoft Defender" to not be replaced.

**Comment by LitKnd** [comment]
I was able to work around this by adding replace text "Contoso, Ltd. Defender for Cloud" to New Text "Microsoft Defender for Cloud" as my final rule, and it worked for me. Not sure if this is a reliable way to handle this?

**Comment by jonburchel** [comment]
Thanks @LitKnd.  Yes, this was a problem, and I think the sample replacement of such a general term was not a great idea in the original implementation!  I removed that now to have more generic default items.  As for the specific problem of replacing text everywhere, your solution seems good!  You can also use Shift+Ctrl+H to invoke the on-page search/replace dialog, so you can individually replace specific instances of a term instead of doing a bulk replace for everything, as the global extension settings will do.
